# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coupon_system.protos import coupon_pb2 as coupon__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coupon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CouponServiceStub(object):
    """优惠券策略服务 — 主接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommend = channel.unary_unary(
                '/coupon.CouponService/Recommend',
                request_serializer=coupon__pb2.RecommendRequest.SerializeToString,
                response_deserializer=coupon__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.QueryUserCoupons = channel.unary_unary(
                '/coupon.CouponService/QueryUserCoupons',
                request_serializer=coupon__pb2.QueryUserCouponsRequest.SerializeToString,
                response_deserializer=coupon__pb2.QueryUserCouponsResponse.FromString,
                _registered_method=True)


class CouponServiceServicer(object):
    """优惠券策略服务 — 主接口
    """

    def Recommend(self, request, context):
        """推荐 + 发放
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryUserCoupons(self, request, context):
        """查询用户优惠券列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CouponServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=coupon__pb2.RecommendRequest.FromString,
                    response_serializer=coupon__pb2.RecommendResponse.SerializeToString,
            ),
            'QueryUserCoupons': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryUserCoupons,
                    request_deserializer=coupon__pb2.QueryUserCouponsRequest.FromString,
                    response_serializer=coupon__pb2.QueryUserCouponsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coupon.CouponService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coupon.CouponService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CouponService(object):
    """优惠券策略服务 — 主接口
    """

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coupon.CouponService/Recommend',
            coupon__pb2.RecommendRequest.SerializeToString,
            coupon__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryUserCoupons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coupon.CouponService/QueryUserCoupons',
            coupon__pb2.QueryUserCouponsRequest.SerializeToString,
            coupon__pb2.QueryUserCouponsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
