# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coupon_system.protos import scoring_pb2 as scoring__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScoringServiceStub(object):
    """打分服务 — 独立 gRPC 服务，接收特征和物料，返回每个 item 的分数
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Score = channel.unary_unary(
                '/scoring.ScoringService/Score',
                request_serializer=scoring__pb2.ScoreRequest.SerializeToString,
                response_deserializer=scoring__pb2.ScoreResponse.FromString,
                _registered_method=True)


class ScoringServiceServicer(object):
    """打分服务 — 独立 gRPC 服务，接收特征和物料，返回每个 item 的分数
    """

    def Score(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Score': grpc.unary_unary_rpc_method_handler(
                    servicer.Score,
                    request_deserializer=scoring__pb2.ScoreRequest.FromString,
                    response_serializer=scoring__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scoring.ScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scoring.ScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoringService(object):
    """打分服务 — 独立 gRPC 服务，接收特征和物料，返回每个 item 的分数
    """

    @staticmethod
    def Score(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scoring.ScoringService/Score',
            scoring__pb2.ScoreRequest.SerializeToString,
            scoring__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
