# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x07scoring\"\xde\x02\n\x0cScoreRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08scene_id\x18\x03 \x01(\x05\x12>\n\ruser_features\x18\x04 \x03(\x0b\x32\'.scoring.ScoreRequest.UserFeaturesEntry\x12\x44\n\x10\x63ontext_features\x18\x05 \x03(\x0b\x32*.scoring.ScoreRequest.ContextFeaturesEntry\x12$\n\x05items\x18\x06 \x03(\x0b\x32\x15.scoring.ItemFeatures\x1a\x33\n\x11UserFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x36\n\x14\x43ontextFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x87\x01\n\x0cItemFeatures\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x35\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32#.scoring.ItemFeatures.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"R\n\rScoreResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\x06scores\x18\x03 \x03(\x0b\x32\x12.scoring.ItemScore\"+\n\tItemScore\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32H\n\x0eScoringService\x12\x36\n\x05Score\x12\x15.scoring.ScoreRequest\x1a\x16.scoring.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST_USERFEATURESENTRY']._loaded_options = None
  _globals['_SCOREREQUEST_USERFEATURESENTRY']._serialized_options = b'8\001'
  _globals['_SCOREREQUEST_CONTEXTFEATURESENTRY']._loaded_options = None
  _globals['_SCOREREQUEST_CONTEXTFEATURESENTRY']._serialized_options = b'8\001'
  _globals['_ITEMFEATURES_FEATURESENTRY']._loaded_options = None
  _globals['_ITEMFEATURES_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_SCOREREQUEST']._serialized_start=27
  _globals['_SCOREREQUEST']._serialized_end=377
  _globals['_SCOREREQUEST_USERFEATURESENTRY']._serialized_start=270
  _globals['_SCOREREQUEST_USERFEATURESENTRY']._serialized_end=321
  _globals['_SCOREREQUEST_CONTEXTFEATURESENTRY']._serialized_start=323
  _globals['_SCOREREQUEST_CONTEXTFEATURESENTRY']._serialized_end=377
  _globals['_ITEMFEATURES']._serialized_start=380
  _globals['_ITEMFEATURES']._serialized_end=515
  _globals['_ITEMFEATURES_FEATURESENTRY']._serialized_start=468
  _globals['_ITEMFEATURES_FEATURESENTRY']._serialized_end=515
  _globals['_SCORERESPONSE']._serialized_start=517
  _globals['_SCORERESPONSE']._serialized_end=599
  _globals['_ITEMSCORE']._serialized_start=601
  _globals['_ITEMSCORE']._serialized_end=644
  _globals['_SCORINGSERVICE']._serialized_start=646
  _globals['_SCORINGSERVICE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
